# Generated by Django 6.0.6 on 2026-06-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
